# Data Parameters
data_path: "/kaggle/input/non-label-data-10k" 
output_dir: "/kaggle/working/dino_output"    
num_workers: 4

# Model Parameters
arch: 'vit_small_patch16_224'
patch_size: 16
out_dim: 8192
norm_last_layer: True
use_bn_in_head: False # DINOHead use_bn parameter

# DINO Specific Hyperparameters
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 10
student_temp: 0.1
center_momentum: 0.9
momentum_teacher: 0.996 

# Training Hyperparameters
epochs: 120
batch_size: 32
learning_rate: 0.001 
min_lr: 0.00001
weight_decay: 0.04
weight_decay_end: 0.4
clip_grad: 3.0
freeze_last_layer: 1 
use_fp16: True
warmup_epochs: 5
init_with_imagenet: True

# Augmentation Parameters
local_crops_number: 8
global_crops_scale: [0.4, 1.0]
local_crops_scale: [0.05, 0.4]

# Logging/Saving
saveckp_freq: 20
seed: 42

# W&B Parameters
wandb_project: "lung_radiology_dino_pretrain" 
wandb_entity: "dvtiendat"  
wandb_run_name: "dino_vit_small_pretrain"