data_path: "sample_data" 
output_dir: "res"          
num_workers: 4
img_size: 224
num_classes: 4
train_split: 0.8
val_split: 0.1 

# Model Parameters
arch: 'vit_small'
patch_size: 16
embed_dim: 384 
num_heads: 6   

pretrain_source: 'random'
pretrained_checkpoint_path: null 
freeze_backbone: 'False' 

# Training Hyperparameters
epochs: 50
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.01
use_fp16: True 

seed: 42
early_stop_patience: 10 

wandb_project: "lung_radiology_classification"
wandb_entity: "dvtiendat"
wandb_run_name: "finetune_vit_dino"